import Head from 'next/head';
import { Inter } from 'next/font/google';
import NavBar from '@/components/NavBar/NavBar';
import Hero from '@/components/Hero/Hero';
import Services from '@/components/Services/Services';
import FeaturedProject from '@/components/FeaturedProject/FeaturedProject';
import Footer from '@/components/Footer/Footer';
import PageTemplate from './PageTemplate/PageTemplate';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Zenith Bygg Consult</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Hero />
      <Services />
      <FeaturedProject />
      <Footer />
      <PageTemplate />
    </>
  );
}
